In [1]:
# 카드 홈페이지 url 모음
sinhan = 'https://www.shinhancard.com/pconts/html/card/credit/MOBFM281/MOBFM281R11.html?crustMenuId=ms581'
kookmin = 'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0047?pageNo=1&cateIdx=1'
samsung = 'https://www.samsungcard.com/home/card/cardinfo/PGHPPDCCardCardinfoRecommendPC001?webViewFirstPage=true'
hyindai = 'https://www.hyundaicard.com/cpc/ma/CPCMA0101_01.hc'
lotte = 'https://www.lottecard.co.kr/app/LPCDADA_V100.lc'
woori = 'https://pc.wooricard.com/dcpc/yh1/crd/crd02/H1CRD202S00.do?ctgrCd=S000017&hiPrdCtgrCd=M110018'
hana = 'https://www.hanacard.co.kr/OPI31000000D.web?schID=pcd&mID=OPI31000005P&CT_ID=241704030444153'

# 신한카드

## 수집할 정보
- 카드 이름
- 카드사
- 출시 일자
- 연회비 정보
- 주요 혜택 및 서비스 내용
- 제휴 대상
- 카드 디자인
- 카드 소개 url

In [2]:
from selenium import webdriver

browser = webdriver.Chrome() 
browser.get(sinhan)

In [32]:
from bs4 import BeautifulSoup
import time
soup = BeautifulSoup(browser.page_source, 'html.parser')

In [33]:
import time
from selenium.webdriver.common.keys import Keys

body = browser.find_elements('css selector', 'body')[0]
soup = BeautifulSoup(browser.page_source, 'html.parser')

card_list = soup.select('#section01_1 > div > div > ul > li')
print(len(card_list))
print()

data_list = []
max_len_fee = 0
max_len_benefit = 0
for card_i in range(len(card_list)):
    card_data = {}
    time.sleep(1)

    card_select = browser.find_elements('css selector', '#section01_1 > div > div > ul > li')
    card_select[card_i].click()
    
    soup = BeautifulSoup(browser.page_source, 'html.parser')
    time.sleep(1)
    soup = BeautifulSoup(browser.page_source, 'html.parser')
    # 카드 이름 수집

    card_data["company"] = soup.select('#container > section > div.bg_gray > div > div.card_jun_info > ul > li')[0].text.replace("회사명 : ", "")
    card_data["title"] = soup.select('#container > section > div.bg_gray > div > div.card_jun_info > ul > li')[1].text.replace("상품명 : ", "")
    card_data["date"] = soup.select('#container > section > div.bg_gray > div > div.card_jun_info > ul > li')[2].text.replace('카드 출시 일자 : ', '')

    # 연회비 정보 수집
    for i in range(3):
        try:
            fee_select = soup.select('#acc0 > div > div > table > tbody > tr')[i]
            card_data[f"fee_brand_{i+1}"] = fee_select.select('span > img')[0]['alt']
            card_data[f"total_fee_{i+1}"] = fee_select.select('td')[4].text
        except IndexError:
            card_data[f"fee_brand_{i+1}"] = None
            card_data[f"total_fee_{i+1}"] = None

            
    benefit_title_counter = 1
    # 혜택 정보 수집
    for i in range(5):
        try:
            benefit_select = soup.select('#section08_0 > div > div > div > ul > li')[i]
            benefit_title = benefit_select.select('a > div > strong')[0].text.strip()

            # "유의사항"이 포함된 제목은 건너뜁니다.
            if "유의사항" in benefit_title:
                # 제목 카운터만 증가시킵니다.
                benefit_title_counter += 1
                continue

            # 제목 저장
            card_data[f"benefit_title_{benefit_title_counter}"] = benefit_title

            # 상세 정보 저장
            benefit_details = benefit_select.select('a > div > ul > li')
            for detail_index in range(2):  # 상세 정보는 최대 2개까지만 저장합니다.
                try:
                    detail_text = benefit_details[detail_index].text.strip()
                    card_data[f"benefit_detail_{benefit_title_counter}_{detail_index+1}"] = detail_text
                except IndexError:
                    card_data[f"benefit_detail_{benefit_title_counter}_{detail_index+1}"] = None

            # 다음 혜택 제목으로 넘어가기 전에 제목 카운터를 증가시킵니다.
            benefit_title_counter += 1

        except IndexError:  # 범위를 벗어나는 경우에 대한 처리
            break
    


    # 이미지,  url
    image = soup.select('#cardCompareAfter > div > div > div > div > div > img')[0]['src']
    card_data['img'] = 'https://www.shinhancard.com'+image
    
    card_data["url"] = soup.select('head > link')[0]['href']
    
    print(card_i+1, card_data['title'])
    data_list.append(card_data)

    browser.back()
    soup = BeautifulSoup(browser.page_source, 'html.parser')
    body = browser.find_elements('css selector', 'body')[0]
    if card_i%6 == 5:
        body.send_keys(Keys.PAGE_DOWN)
        
    soup = BeautifulSoup(browser.page_source, 'html.parser')

93

1 신한카드 봄
2 신한카드 봄(도구리)
3 신한카드 Globus
4 신한카드 플리
5 신한카드 플리(산리오캐릭터즈)
6 신한카드 핏(Fit)
7 신한카드 EVerywhere
8 신한카드 Eats More(곰표)
9 신한카드 Eats More(이츠모아)
10 신한카드 Unboxing
11 신한카드 래플(Raffle)
12 신한카드 Deep Dream(모베러웍스)
13 신한카드 구독 좋아요
14 신한카드 Puzzle
15 #Pay 신한카드
16 신한카드 알뜰More(알뜰모아)
17 위버스 신한카드(BTS)
18 신한카드 Deep Oil
19 수소차 충전할인 신한카드
20 티머니 Pay & GO 신한카드
21 아시아나 신한카드 Air 1.5
22 신한카드 MY CAR
23 신한카드 국민행복
24 IKEA for Business with 신한카드
25 신한카드 YaY
26 신한카드 My TeenS
27 신한카드 RPM+ Platinum#
28 신한카드 Air One
29 신한카드 혼디모앙
30 땡겨요 신한카드
31 신한카드 Deep Dream
32 신한카드 Deep Dream Platinum+
33 신한카드 Deep Store
34 신한카드 Deep Making
35 신한카드 Deep Taking
36 신한카드 Deep On Platinum+
37 신한카드 Deep Once
38 신한카드 Deep Once Plus
39 신한카드 YOLO ⓘ
40 신한카드 B.Big(삑)
41 신한카드 Mr.Life
42 신한카드 Hi-Point
43 신한카드 Simple+
44 신한카드 Shopping
45 신한 햇살론카드
46 신한카드 Edu
47 신한카드 주거래 신용
48 신한카드 Air Platinum#
49 신한카드 Lesson Platinum#
50 신한카드 Simple Platinum#
51 신한카드 Cube Platinum#
52 신한카드 Love Platinum#
53 GS칼텍스 신한카드 Shine
54 신한카드 후불하이패스+ (하이패스 전용)
55 신한카드 후불하이패스+(SIM형)
56 (배민커넥트) 신한카드 Deep Oil
57 BC 부자되세요 홈쇼핑 신한카드
58 신한카드 아름다운
59 신한카드 아이행복
60 신한카드 Ownership
61 E1 개인택시운송사업자 신한카드
62 신한카드 경차사랑 Life
63 신한카드 Hi-Point MyShop
64 신한카드 EV
65 신한카드 Hi-Point MyShop PLATINUM#
66 청년동행 신한카드 B.Big(삑)
67 큰수레 비즈니스 신한카드 Simple+
68 신한카드 집
69 국세청 복지 GS칼텍스 신한카드 Shine
70 국세청 복지 신한카드 Lady
71 공무원연금복지 GS칼텍스 신한카드 Shine
72 공무원연금복지 SK에너지 신한카드 Oiling
73 장애인 통합복지 신한카드 2030
74 장애인 통합복지 신한카드 Lady
75 신한카드 Shopping(한국유치원총연합회 교원증)
76 대한치과위생사협회 신한카드 Lady
77 대한치과위생사협회 GS칼텍스 신한카드 BigPlus
78 알뜰교통 신한카드
79 SK55 화물복지 신한카드
80 화물운전자복지 신한카드
81 SK에너지 2MORE 화물복지 신한카드
82 알뜰주유소 화물운전자복지 신한카드
83 HD현대오일뱅크 2UP 화물운전자복지 신한카드
84 S-OIL 2UP 화물운전자복지 신한카드
85 노란우산 신한카드
86 개인택시운송자사업자 신한카드 T-플러스
87 S.Sing 씽화물복지 신한카드
88 외식가족공제 신한카드 Hi-Point MyShop
89 교직원복지 신한카드 Love
90 한국수력원자력 임직원복지 신한카드 LOVE
91 SK One+ 화물복지 신한카드
92 부산가족사랑 GS칼텍스 신한카드 Shine
93 119 소방사랑 GS칼텍스 신한카드 BigPlus

In [34]:
import pandas as pd
df = pd.DataFrame(data_list)
df.head()

,company,title,date,fee_brand_1,total_fee_1,fee_brand_2,total_fee_2,fee_brand_3,total_fee_3,benefit_title_1,...,benefit_detail_3_1,benefit_detail_3_2,img,url,benefit_title_4,benefit_detail_4_1,benefit_detail_4_2,benefit_title_5,benefit_detail_5_1,benefit_detail_5_2
0,신한카드,신한카드 봄,2023.03.20,국내 카드,1만7천원,마스터 카드,2만원,None,None,기본 서비스,...,None,None,https://www.shinhancard.com/pconts/images/cont...,https://www.shinhancard.com/pconts/html/card/a...,NaN,NaN,NaN,NaN,NaN,NaN
1,신한카드,신한카드 봄(도구리),2023.03.20,국내 카드,1만7천원,마스터 카드,2만원,None,None,기본 서비스,...,None,None,https://www.shinhancard.com/pconts/images/cont...,https://www.shinhancard.com/pconts/html/card/a...,NaN,NaN,NaN,NaN,NaN,NaN
2,신한카드,신한카드 Globus,2023.04.18,국내 카드,2만2천원,마스터 카드,2만5천원,None,None,해외 수수료 할인,...,NaN,NaN,https://www.shinhancard.com/pconts/images/cont...,https://www.shinhancard.com/pconts/html/card/a...,Platinum,국제 브랜드사 서비스(플래티늄 등급 선택 시 제공),None,NaN,NaN,NaN
3,신한카드,신한카드 플리,2022.05.18,국내 카드,1만5천원,마스터 카드,1만8천원,None,None,Daily 결제일 할인,...,"My Pick 가맹점 월 3, 6, 9번째 이용 건 마이신한포인트 1,000포인트 ...",None,https://www.shinhancard.com/pconts/images/cont...,https://www.shinhancard.com/pconts/html/card/a...,NaN,NaN,NaN,NaN,NaN,NaN
4,신한카드,신한카드 플리(산리오캐릭터즈),2022.05.18,국내 카드,1만5천원,마스터 카드,1만8천원,None,None,Daily 결제일 할인,...,"My Pick 가맹점 월 3, 6, 9번째 이용 건 마이신한포인트 1,000포인트 ...",None,https://www.shinhancard.com/pconts/images/cont...,https://www.shinhancard.com/pconts/html/card/a...,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   company             93 non-null     object
 1   title               93 non-null     object
 2   date                93 non-null     object
 3   fee_brand_1         93 non-null     object
 4   total_fee_1         93 non-null     object
 5   fee_brand_2         77 non-null     object
 6   total_fee_2         77 non-null     object
 7   fee_brand_3         14 non-null     object
 8   total_fee_3         14 non-null     object
 9   benefit_title_1     93 non-null     object
 10  benefit_detail_1_1  82 non-null     object
 11  benefit_detail_1_2  48 non-null     object
 12  benefit_title_2     92 non-null     object
 13  benefit_detail_2_1  79 non-null     object
 14  benefit_detail_2_2  39 non-null     object
 15  benefit_title_3     82 non-null     object
 16  benefit_detail_3_1  71 non-null     object
 17  benefit_detail_3_2  33 non-null     object
 18  img                 93 non-null     object
 19  url                 93 non-null     object
 20  benefit_title_4     52 non-null     object
 21  benefit_detail_4_1  44 non-null     object
 22  benefit_detail_4_2  19 non-null     object
 23  benefit_title_5     40 non-null     object
 24  benefit_detail_5_1  37 non-null     object
 25  benefit_detail_5_2  19 non-null     object
dtypes: object(26)
memory usage: 19.0+ KB

In [36]:
df.shape

(93, 26)

In [37]:
# 'image'와 'url' 열을 제외한 나머지 열을 선택합니다.
columns = [col for col in df if col not in ['img', 'url']]

# 이제 'image'와 'url' 열을 뒤에 추가합니다.
df = df[columns + ['img', 'url']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   company             93 non-null     object
 1   title               93 non-null     object
 2   date                93 non-null     object
 3   fee_brand_1         93 non-null     object
 4   total_fee_1         93 non-null     object
 5   fee_brand_2         77 non-null     object
 6   total_fee_2         77 non-null     object
 7   fee_brand_3         14 non-null     object
 8   total_fee_3         14 non-null     object
 9   benefit_title_1     93 non-null     object
 10  benefit_detail_1_1  82 non-null     object
 11  benefit_detail_1_2  48 non-null     object
 12  benefit_title_2     92 non-null     object
 13  benefit_detail_2_1  79 non-null     object
 14  benefit_detail_2_2  39 non-null     object
 15  benefit_title_3     82 non-null     object
 16  benefit_detail_3_1  71 non-null     object
 17  benefit_detail_3_2  33 non-null     object
 18  benefit_title_4     52 non-null     object
 19  benefit_detail_4_1  44 non-null     object
 20  benefit_detail_4_2  19 non-null     object
 21  benefit_title_5     40 non-null     object
 22  benefit_detail_5_1  37 non-null     object
 23  benefit_detail_5_2  19 non-null     object
 24  img                 93 non-null     object
 25  url                 93 non-null     object
dtypes: object(26)
memory usage: 19.0+ KB

In [38]:
df.to_csv('sinhancard_result.csv', index=False)